// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: kira/slashing/v1beta1/tx.proto

package types

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgActivate defines the Msg/Activate request type
type MsgActivate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidatorAddr string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (x *MsgActivate) Reset() {
	*x = MsgActivate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgActivate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgActivate) ProtoMessage() {}

func (x *MsgActivate) ProtoReflect() protoreflect.Message {
	mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgActivate.ProtoReflect.Descriptor instead.
func (*MsgActivate) Descriptor() ([]byte, []int) {
	return file_kira_slashing_v1beta1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgActivate) GetValidatorAddr() string {
	if x != nil {
		return x.ValidatorAddr
	}
	return ""
}

// MsgActivateResponse defines the Msg/Activate response type
type MsgActivateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgActivateResponse) Reset() {
	*x = MsgActivateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgActivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgActivateResponse) ProtoMessage() {}

func (x *MsgActivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgActivateResponse.ProtoReflect.Descriptor instead.
func (*MsgActivateResponse) Descriptor() ([]byte, []int) {
	return file_kira_slashing_v1beta1_tx_proto_rawDescGZIP(), []int{1}
}

// MsgPause defines the Msg/Pause request type
type MsgPause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidatorAddr string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (x *MsgPause) Reset() {
	*x = MsgPause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPause) ProtoMessage() {}

func (x *MsgPause) ProtoReflect() protoreflect.Message {
	mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPause.ProtoReflect.Descriptor instead.
func (*MsgPause) Descriptor() ([]byte, []int) {
	return file_kira_slashing_v1beta1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgPause) GetValidatorAddr() string {
	if x != nil {
		return x.ValidatorAddr
	}
	return ""
}

// MsgUnpauseResponse defines the Msg/Unpause response type
type MsgPauseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPauseResponse) Reset() {
	*x = MsgPauseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPauseResponse) ProtoMessage() {}

func (x *MsgPauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPauseResponse.ProtoReflect.Descriptor instead.
func (*MsgPauseResponse) Descriptor() ([]byte, []int) {
	return file_kira_slashing_v1beta1_tx_proto_rawDescGZIP(), []int{3}
}

// MsgUnpause defines the Msg/Unpause request type
type MsgUnpause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValidatorAddr string `protobuf:"bytes,1,opt,name=validator_addr,json=validatorAddr,proto3" json:"validator_addr,omitempty"`
}

func (x *MsgUnpause) Reset() {
	*x = MsgUnpause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUnpause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUnpause) ProtoMessage() {}

func (x *MsgUnpause) ProtoReflect() protoreflect.Message {
	mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUnpause.ProtoReflect.Descriptor instead.
func (*MsgUnpause) Descriptor() ([]byte, []int) {
	return file_kira_slashing_v1beta1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgUnpause) GetValidatorAddr() string {
	if x != nil {
		return x.ValidatorAddr
	}
	return ""
}

// MsgUnpauseResponse defines the Msg/Unpause response type
type MsgUnpauseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgUnpauseResponse) Reset() {
	*x = MsgUnpauseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUnpauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUnpauseResponse) ProtoMessage() {}

func (x *MsgUnpauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUnpauseResponse.ProtoReflect.Descriptor instead.
func (*MsgUnpauseResponse) Descriptor() ([]byte, []int) {
	return file_kira_slashing_v1beta1_tx_proto_rawDescGZIP(), []int{5}
}

// only validator whose staking pool is being
// slashed should be able to submit refute transaction containing a string
// (max 2048 characters) with URL or CID explaining the circumstances under
// which the fault occured. The refutation string should be then attached to
// the Slashing Proposal for all voters too see.
type MsgRefuteSlashingProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender     string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Validator  string `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator,omitempty"`
	Refutation string `protobuf:"bytes,3,opt,name=refutation,proto3" json:"refutation,omitempty"`
}

func (x *MsgRefuteSlashingProposal) Reset() {
	*x = MsgRefuteSlashingProposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRefuteSlashingProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRefuteSlashingProposal) ProtoMessage() {}

func (x *MsgRefuteSlashingProposal) ProtoReflect() protoreflect.Message {
	mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRefuteSlashingProposal.ProtoReflect.Descriptor instead.
func (*MsgRefuteSlashingProposal) Descriptor() ([]byte, []int) {
	return file_kira_slashing_v1beta1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgRefuteSlashingProposal) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgRefuteSlashingProposal) GetValidator() string {
	if x != nil {
		return x.Validator
	}
	return ""
}

func (x *MsgRefuteSlashingProposal) GetRefutation() string {
	if x != nil {
		return x.Refutation
	}
	return ""
}

type MsgRefuteSlashingProposalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgRefuteSlashingProposalResponse) Reset() {
	*x = MsgRefuteSlashingProposalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRefuteSlashingProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRefuteSlashingProposalResponse) ProtoMessage() {}

func (x *MsgRefuteSlashingProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kira_slashing_v1beta1_tx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRefuteSlashingProposalResponse.ProtoReflect.Descriptor instead.
func (*MsgRefuteSlashingProposalResponse) Descriptor() ([]byte, []int) {
	return file_kira_slashing_v1beta1_tx_proto_rawDescGZIP(), []int{7}
}

var File_kira_slashing_v1beta1_tx_proto protoreflect.FileDescriptor

var file_kira_slashing_v1beta1_tx_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6b, 0x69, 0x72, 0x61, 0x2f, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2f,
	0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x6b, 0x69, 0x72, 0x61, 0x2e, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x1a,
	0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x6b, 0x69, 0x72, 0x61, 0x2f, 0x73, 0x6c, 0x61, 0x73,
	0x68, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x70, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x0b, 0x4d,
	0x73, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x0e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x1d, 0xea, 0xde, 0x1f, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0xf2,
	0xde, 0x1f, 0x0e, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x52, 0x0d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x3a, 0x08, 0x88, 0xa0, 0x1f, 0x00, 0x98, 0xa0, 0x1f, 0x01, 0x22, 0x15, 0x0a, 0x13, 0x4d, 0x73,
	0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x5a, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x44, 0x0a,
	0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1d, 0xea, 0xde, 0x1f, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0xf2, 0xde, 0x1f, 0x0e, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x52, 0x0d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x3a, 0x08, 0x88, 0xa0, 0x1f, 0x00, 0x98, 0xa0, 0x1f, 0x01, 0x22, 0x12, 0x0a,
	0x10, 0x4d, 0x73, 0x67, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x5c, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x12,
	0x44, 0x0a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x1d, 0xea, 0xde, 0x1f, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0xf2, 0xde, 0x1f, 0x0e, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x52, 0x0d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x3a, 0x08, 0x88, 0xa0, 0x1f, 0x00, 0x98, 0xa0, 0x1f, 0x01, 0x22,
	0x14, 0x0a, 0x12, 0x4d, 0x73, 0x67, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x71, 0x0a, 0x19, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x66, 0x75,
	0x74, 0x65, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x66, 0x75,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x66, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x23, 0x0a, 0x21, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x66, 0x75, 0x74, 0x65, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd3, 0x02,
	0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x4a, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x2e, 0x6b, 0x69, 0x72, 0x61, 0x2e, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e,
	0x67, 0x2e, 0x4d, 0x73, 0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x1a, 0x22, 0x2e,
	0x6b, 0x69, 0x72, 0x61, 0x2e, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x73,
	0x67, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x05, 0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x17, 0x2e, 0x6b, 0x69, 0x72,
	0x61, 0x2e, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x50, 0x61,
	0x75, 0x73, 0x65, 0x1a, 0x1f, 0x2e, 0x6b, 0x69, 0x72, 0x61, 0x2e, 0x73, 0x6c, 0x61, 0x73, 0x68,
	0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x50, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x07, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x12,
	0x19, 0x2e, 0x6b, 0x69, 0x72, 0x61, 0x2e, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e,
	0x4d, 0x73, 0x67, 0x55, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x1a, 0x21, 0x2e, 0x6b, 0x69, 0x72,
	0x61, 0x2e, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x55, 0x6e,
	0x70, 0x61, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x74, 0x0a,
	0x16, 0x52, 0x65, 0x66, 0x75, 0x74, 0x65, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x50,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x28, 0x2e, 0x6b, 0x69, 0x72, 0x61, 0x2e, 0x73,
	0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x66, 0x75, 0x74,
	0x65, 0x53, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x1a, 0x30, 0x2e, 0x6b, 0x69, 0x72, 0x61, 0x2e, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e,
	0x67, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x66, 0x75, 0x74, 0x65, 0x53, 0x6c, 0x61, 0x73, 0x68,
	0x69, 0x6e, 0x67, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4b, 0x69, 0x72, 0x61, 0x43, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x6b, 0x61, 0x69,
	0x2f, 0x78, 0x2f, 0x73, 0x6c, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0xa8, 0xe2, 0x1e, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kira_slashing_v1beta1_tx_proto_rawDescOnce sync.Once
	file_kira_slashing_v1beta1_tx_proto_rawDescData = file_kira_slashing_v1beta1_tx_proto_rawDesc
)

func file_kira_slashing_v1beta1_tx_proto_rawDescGZIP() []byte {
	file_kira_slashing_v1beta1_tx_proto_rawDescOnce.Do(func() {
		file_kira_slashing_v1beta1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_kira_slashing_v1beta1_tx_proto_rawDescData)
	})
	return file_kira_slashing_v1beta1_tx_proto_rawDescData
}

var file_kira_slashing_v1beta1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kira_slashing_v1beta1_tx_proto_goTypes = []interface{}{
	(*MsgActivate)(nil),                       // 0: kira.slashing.MsgActivate
	(*MsgActivateResponse)(nil),               // 1: kira.slashing.MsgActivateResponse
	(*MsgPause)(nil),                          // 2: kira.slashing.MsgPause
	(*MsgPauseResponse)(nil),                  // 3: kira.slashing.MsgPauseResponse
	(*MsgUnpause)(nil),                        // 4: kira.slashing.MsgUnpause
	(*MsgUnpauseResponse)(nil),                // 5: kira.slashing.MsgUnpauseResponse
	(*MsgRefuteSlashingProposal)(nil),         // 6: kira.slashing.MsgRefuteSlashingProposal
	(*MsgRefuteSlashingProposalResponse)(nil), // 7: kira.slashing.MsgRefuteSlashingProposalResponse
}
var file_kira_slashing_v1beta1_tx_proto_depIdxs = []int32{
	0, // 0: kira.slashing.Msg.Activate:input_type -> kira.slashing.MsgActivate
	2, // 1: kira.slashing.Msg.Pause:input_type -> kira.slashing.MsgPause
	4, // 2: kira.slashing.Msg.Unpause:input_type -> kira.slashing.MsgUnpause
	6, // 3: kira.slashing.Msg.RefuteSlashingProposal:input_type -> kira.slashing.MsgRefuteSlashingProposal
	1, // 4: kira.slashing.Msg.Activate:output_type -> kira.slashing.MsgActivateResponse
	3, // 5: kira.slashing.Msg.Pause:output_type -> kira.slashing.MsgPauseResponse
	5, // 6: kira.slashing.Msg.Unpause:output_type -> kira.slashing.MsgUnpauseResponse
	7, // 7: kira.slashing.Msg.RefuteSlashingProposal:output_type -> kira.slashing.MsgRefuteSlashingProposalResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kira_slashing_v1beta1_tx_proto_init() }
func file_kira_slashing_v1beta1_tx_proto_init() {
	if File_kira_slashing_v1beta1_tx_proto != nil {
		return
	}
	file_kira_slashing_v1beta1_proposal_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kira_slashing_v1beta1_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgActivate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_slashing_v1beta1_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgActivateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_slashing_v1beta1_tx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_slashing_v1beta1_tx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPauseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_slashing_v1beta1_tx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUnpause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_slashing_v1beta1_tx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUnpauseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_slashing_v1beta1_tx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRefuteSlashingProposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_slashing_v1beta1_tx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRefuteSlashingProposalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kira_slashing_v1beta1_tx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kira_slashing_v1beta1_tx_proto_goTypes,
		DependencyIndexes: file_kira_slashing_v1beta1_tx_proto_depIdxs,
		MessageInfos:      file_kira_slashing_v1beta1_tx_proto_msgTypes,
	}.Build()
	File_kira_slashing_v1beta1_tx_proto = out.File
	file_kira_slashing_v1beta1_tx_proto_rawDesc = nil
	file_kira_slashing_v1beta1_tx_proto_goTypes = nil
	file_kira_slashing_v1beta1_tx_proto_depIdxs = nil
}
