// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: kira/ethereum/ethereum.proto

package types

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EVMTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From     string `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To       string `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Gas      string `protobuf:"bytes,4,opt,name=Gas,proto3" json:"Gas,omitempty"`
	GasPrice string `protobuf:"bytes,5,opt,name=GasPrice,proto3" json:"GasPrice,omitempty"`
	Nonce    string `protobuf:"bytes,6,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Data     string `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
	ChainId  int64  `protobuf:"varint,8,opt,name=ChainId,proto3" json:"ChainId,omitempty"`
	V        string `protobuf:"bytes,9,opt,name=V,proto3" json:"V,omitempty"`
	R        string `protobuf:"bytes,10,opt,name=R,proto3" json:"R,omitempty"`
	S        string `protobuf:"bytes,11,opt,name=S,proto3" json:"S,omitempty"`
}

func (x *EVMTx) Reset() {
	*x = EVMTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_ethereum_ethereum_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EVMTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EVMTx) ProtoMessage() {}

func (x *EVMTx) ProtoReflect() protoreflect.Message {
	mi := &file_kira_ethereum_ethereum_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EVMTx.ProtoReflect.Descriptor instead.
func (*EVMTx) Descriptor() ([]byte, []int) {
	return file_kira_ethereum_ethereum_proto_rawDescGZIP(), []int{0}
}

func (x *EVMTx) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EVMTx) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EVMTx) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EVMTx) GetGas() string {
	if x != nil {
		return x.Gas
	}
	return ""
}

func (x *EVMTx) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *EVMTx) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *EVMTx) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *EVMTx) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *EVMTx) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

func (x *EVMTx) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *EVMTx) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

var File_kira_ethereum_ethereum_proto protoreflect.FileDescriptor

var file_kira_ethereum_ethereum_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6b, 0x69, 0x72, 0x61, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f,
	0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x6b, 0x69, 0x72, 0x61, 0x2e, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x1a, 0x14, 0x67,
	0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdd,
	0x01, 0x0a, 0x05, 0x45, 0x56, 0x4d, 0x54, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x14, 0x0a, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x47, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x47, 0x61, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x68, 0x61,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x56, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x01, 0x56, 0x12, 0x0c, 0x0a, 0x01, 0x52, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x52,
	0x12, 0x0c, 0x0a, 0x01, 0x53, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x53, 0x42, 0x2c,
	0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x69, 0x72,
	0x61, 0x43, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x6b, 0x61, 0x69, 0x2f, 0x78, 0x2f, 0x65, 0x74,
	0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kira_ethereum_ethereum_proto_rawDescOnce sync.Once
	file_kira_ethereum_ethereum_proto_rawDescData = file_kira_ethereum_ethereum_proto_rawDesc
)

func file_kira_ethereum_ethereum_proto_rawDescGZIP() []byte {
	file_kira_ethereum_ethereum_proto_rawDescOnce.Do(func() {
		file_kira_ethereum_ethereum_proto_rawDescData = protoimpl.X.CompressGZIP(file_kira_ethereum_ethereum_proto_rawDescData)
	})
	return file_kira_ethereum_ethereum_proto_rawDescData
}

var file_kira_ethereum_ethereum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_kira_ethereum_ethereum_proto_goTypes = []interface{}{
	(*EVMTx)(nil), // 0: kira.ethereum.EVMTx
}
var file_kira_ethereum_ethereum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kira_ethereum_ethereum_proto_init() }
func file_kira_ethereum_ethereum_proto_init() {
	if File_kira_ethereum_ethereum_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kira_ethereum_ethereum_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EVMTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kira_ethereum_ethereum_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kira_ethereum_ethereum_proto_goTypes,
		DependencyIndexes: file_kira_ethereum_ethereum_proto_depIdxs,
		MessageInfos:      file_kira_ethereum_ethereum_proto_msgTypes,
	}.Build()
	File_kira_ethereum_ethereum_proto = out.File
	file_kira_ethereum_ethereum_proto_rawDesc = nil
	file_kira_ethereum_ethereum_proto_goTypes = nil
	file_kira_ethereum_ethereum_proto_depIdxs = nil
}
