services:
  manager:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9000:9000/udp"
    networks:
      - interx-manager
    volumes:
      - "./config.yml:/srv/config.yml"
      - "./logs:/srv/logs"
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  interx-manager:
    name: interx_default
    external: true
