// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: kira/layer2/proposal.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Allows joining applications as executor or fisherman. By default all
// executors are also verifiers so it should not be possible to set both
// executor and verifier flags to true at the same time. This tx MUST also allow
// to define or update a globally unique INTERX address that will be tasked with
// operating the application. Tx should also fail if someone already joined
// application and is applying for a different role, in other words all
// operators must be unique for each dApp although different applications can
// have the same operators.
type ProposalJoinDapp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender   string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	DappName string `protobuf:"bytes,2,opt,name=dapp_name,json=dappName,proto3" json:"dapp_name,omitempty"`
	Executor bool   `protobuf:"varint,3,opt,name=executor,proto3" json:"executor,omitempty"` // can only be set by validators, raises proposal that controllers must approve
	Verifier bool   `protobuf:"varint,4,opt,name=verifier,proto3" json:"verifier,omitempty"` // can be set by anyone, sending this tx does not require any approvals however requires a bond in `lp_<denom>` tokens no less than `dapp_verifier_bond`
	Interx   string `protobuf:"bytes,5,opt,name=interx,proto3" json:"interx,omitempty"`      // must be set to a valid kira address
}

func (x *ProposalJoinDapp) Reset() {
	*x = ProposalJoinDapp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_layer2_proposal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalJoinDapp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalJoinDapp) ProtoMessage() {}

func (x *ProposalJoinDapp) ProtoReflect() protoreflect.Message {
	mi := &file_kira_layer2_proposal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalJoinDapp.ProtoReflect.Descriptor instead.
func (*ProposalJoinDapp) Descriptor() ([]byte, []int) {
	return file_kira_layer2_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *ProposalJoinDapp) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ProposalJoinDapp) GetDappName() string {
	if x != nil {
		return x.DappName
	}
	return ""
}

func (x *ProposalJoinDapp) GetExecutor() bool {
	if x != nil {
		return x.Executor
	}
	return false
}

func (x *ProposalJoinDapp) GetVerifier() bool {
	if x != nil {
		return x.Verifier
	}
	return false
}

func (x *ProposalJoinDapp) GetInterx() string {
	if x != nil {
		return x.Interx
	}
	return ""
}

// can only be sent by the dApp controllers, allowing to upgrade binaries,
// controlled and modify all other properties
type ProposalUpsertDapp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Dapp   *Dapp  `protobuf:"bytes,2,opt,name=dapp,proto3" json:"dapp,omitempty"`
}

func (x *ProposalUpsertDapp) Reset() {
	*x = ProposalUpsertDapp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_layer2_proposal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalUpsertDapp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalUpsertDapp) ProtoMessage() {}

func (x *ProposalUpsertDapp) ProtoReflect() protoreflect.Message {
	mi := &file_kira_layer2_proposal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalUpsertDapp.ProtoReflect.Descriptor instead.
func (*ProposalUpsertDapp) Descriptor() ([]byte, []int) {
	return file_kira_layer2_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *ProposalUpsertDapp) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ProposalUpsertDapp) GetDapp() *Dapp {
	if x != nil {
		return x.Dapp
	}
	return nil
}

var File_kira_layer2_proposal_proto protoreflect.FileDescriptor

var file_kira_layer2_proposal_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6b, 0x69, 0x72, 0x61, 0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x2f, 0x70, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6b, 0x69,
	0x72, 0x61, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x19, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x6b, 0x69, 0x72, 0x61,
	0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x61, 0x70, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x78,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x78, 0x3a, 0x0f,
	0xe8, 0xa0, 0x1f, 0x01, 0xca, 0xb4, 0x2d, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x59, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x55, 0x70, 0x73, 0x65, 0x72,
	0x74, 0x44, 0x61, 0x70, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x2b, 0x0a,
	0x04, 0x64, 0x61, 0x70, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6b, 0x69,
	0x72, 0x61, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32, 0x2e, 0x44, 0x61, 0x70, 0x70, 0x42, 0x04,
	0xc8, 0xde, 0x1f, 0x00, 0x52, 0x04, 0x64, 0x61, 0x70, 0x70, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x69, 0x72, 0x61, 0x43, 0x6f, 0x72,
	0x65, 0x2f, 0x73, 0x65, 0x6b, 0x61, 0x69, 0x2f, 0x78, 0x2f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x32,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kira_layer2_proposal_proto_rawDescOnce sync.Once
	file_kira_layer2_proposal_proto_rawDescData = file_kira_layer2_proposal_proto_rawDesc
)

func file_kira_layer2_proposal_proto_rawDescGZIP() []byte {
	file_kira_layer2_proposal_proto_rawDescOnce.Do(func() {
		file_kira_layer2_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(file_kira_layer2_proposal_proto_rawDescData)
	})
	return file_kira_layer2_proposal_proto_rawDescData
}

var file_kira_layer2_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kira_layer2_proposal_proto_goTypes = []interface{}{
	(*ProposalJoinDapp)(nil),   // 0: kira.layer2.ProposalJoinDapp
	(*ProposalUpsertDapp)(nil), // 1: kira.layer2.ProposalUpsertDapp
	(*Dapp)(nil),               // 2: kira.layer2.Dapp
}
var file_kira_layer2_proposal_proto_depIdxs = []int32{
	2, // 0: kira.layer2.ProposalUpsertDapp.dapp:type_name -> kira.layer2.Dapp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kira_layer2_proposal_proto_init() }
func file_kira_layer2_proposal_proto_init() {
	if File_kira_layer2_proposal_proto != nil {
		return
	}
	file_kira_layer2_layer2_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kira_layer2_proposal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalJoinDapp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_layer2_proposal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalUpsertDapp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kira_layer2_proposal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kira_layer2_proposal_proto_goTypes,
		DependencyIndexes: file_kira_layer2_proposal_proto_depIdxs,
		MessageInfos:      file_kira_layer2_proposal_proto_msgTypes,
	}.Build()
	File_kira_layer2_proposal_proto = out.File
	file_kira_layer2_proposal_proto_rawDesc = nil
	file_kira_layer2_proposal_proto_goTypes = nil
	file_kira_layer2_proposal_proto_depIdxs = nil
}
