// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: kira/ubi/proposal.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpsertUBIProposal a proposal to create a new or modify existing UBI registry
// record. The proposal should fail if sum of all ((float)amount / period) *
// 31556952 for all UBI records is greater than ubi-hard-cap.
type UpsertUBIProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// distribution-start & distribution-end - defines the exact time period (Unix
	// timestamps) between which tokens will be distributed to the pool, allowing
	// for a precise funds spending.
	DistributionStart uint64 `protobuf:"varint,2,opt,name=distribution_start,json=distributionStart,proto3" json:"distribution_start,omitempty"` // <unix-timestamp>
	DistributionEnd   uint64 `protobuf:"varint,3,opt,name=distribution_end,json=distributionEnd,proto3" json:"distribution_end,omitempty"`       // <unix-timestamp>
	// amount - the amount of KEX tokens to be minted and distributed every period
	// number of seconds into pool
	Amount uint64 `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// period - time in seconds that must elapse sincedistribution-last
	// for the funds to be distributed automatically into pool
	Period uint64 `protobuf:"varint,5,opt,name=period,proto3" json:"period,omitempty"` // <seconds>
	// pool - spending pool name where exact amount of KEX should be deposited
	Pool string `protobuf:"bytes,6,opt,name=pool,proto3" json:"pool,omitempty"`
}

func (x *UpsertUBIProposal) Reset() {
	*x = UpsertUBIProposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_ubi_proposal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertUBIProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertUBIProposal) ProtoMessage() {}

func (x *UpsertUBIProposal) ProtoReflect() protoreflect.Message {
	mi := &file_kira_ubi_proposal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertUBIProposal.ProtoReflect.Descriptor instead.
func (*UpsertUBIProposal) Descriptor() ([]byte, []int) {
	return file_kira_ubi_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertUBIProposal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertUBIProposal) GetDistributionStart() uint64 {
	if x != nil {
		return x.DistributionStart
	}
	return 0
}

func (x *UpsertUBIProposal) GetDistributionEnd() uint64 {
	if x != nil {
		return x.DistributionEnd
	}
	return 0
}

func (x *UpsertUBIProposal) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpsertUBIProposal) GetPeriod() uint64 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *UpsertUBIProposal) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

// RemoveUBIProposal - a proposal to delete UBI record
type RemoveUBIProposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UbiName string `protobuf:"bytes,1,opt,name=ubi_name,json=ubiName,proto3" json:"ubi_name,omitempty"`
}

func (x *RemoveUBIProposal) Reset() {
	*x = RemoveUBIProposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_ubi_proposal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveUBIProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUBIProposal) ProtoMessage() {}

func (x *RemoveUBIProposal) ProtoReflect() protoreflect.Message {
	mi := &file_kira_ubi_proposal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUBIProposal.ProtoReflect.Descriptor instead.
func (*RemoveUBIProposal) Descriptor() ([]byte, []int) {
	return file_kira_ubi_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveUBIProposal) GetUbiName() string {
	if x != nil {
		return x.UbiName
	}
	return ""
}

var File_kira_ubi_proposal_proto protoreflect.FileDescriptor

var file_kira_ubi_proposal_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6b, 0x69, 0x72, 0x61, 0x2f, 0x75, 0x62, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6b, 0x69, 0x72, 0x61, 0x2e,
	0x75, 0x62, 0x69, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x12, 0x6b, 0x69, 0x72, 0x61, 0x2f, 0x75, 0x62, 0x69, 0x2f, 0x75, 0x62, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x55,
	0x42, 0x49, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2d,
	0x0a, 0x12, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x29, 0x0a,
	0x10, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x6e,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6f, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x3a, 0x0f, 0xe8, 0xa0,
	0x1f, 0x01, 0xca, 0xb4, 0x2d, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3f, 0x0a,
	0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x42, 0x49, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x62, 0x69, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x62, 0x69, 0x4e, 0x61, 0x6d, 0x65, 0x3a, 0x0f, 0xe8,
	0xa0, 0x1f, 0x01, 0xca, 0xb4, 0x2d, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x27,
	0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b, 0x69, 0x72,
	0x61, 0x43, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x6b, 0x61, 0x69, 0x2f, 0x78, 0x2f, 0x75, 0x62,
	0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kira_ubi_proposal_proto_rawDescOnce sync.Once
	file_kira_ubi_proposal_proto_rawDescData = file_kira_ubi_proposal_proto_rawDesc
)

func file_kira_ubi_proposal_proto_rawDescGZIP() []byte {
	file_kira_ubi_proposal_proto_rawDescOnce.Do(func() {
		file_kira_ubi_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(file_kira_ubi_proposal_proto_rawDescData)
	})
	return file_kira_ubi_proposal_proto_rawDescData
}

var file_kira_ubi_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kira_ubi_proposal_proto_goTypes = []interface{}{
	(*UpsertUBIProposal)(nil), // 0: kira.ubi.UpsertUBIProposal
	(*RemoveUBIProposal)(nil), // 1: kira.ubi.RemoveUBIProposal
}
var file_kira_ubi_proposal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kira_ubi_proposal_proto_init() }
func file_kira_ubi_proposal_proto_init() {
	if File_kira_ubi_proposal_proto != nil {
		return
	}
	file_kira_ubi_ubi_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kira_ubi_proposal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertUBIProposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_ubi_proposal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveUBIProposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kira_ubi_proposal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kira_ubi_proposal_proto_goTypes,
		DependencyIndexes: file_kira_ubi_proposal_proto_depIdxs,
		MessageInfos:      file_kira_ubi_proposal_proto_msgTypes,
	}.Build()
	File_kira_ubi_proposal_proto = out.File
	file_kira_ubi_proposal_proto_rawDesc = nil
	file_kira_ubi_proposal_proto_goTypes = nil
	file_kira_ubi_proposal_proto_depIdxs = nil
}
