// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: kira/ubi/query.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_QueryUBIRecords_FullMethodName      = "/kira.ubi.Query/QueryUBIRecords"
	Query_QueryUBIRecordByName_FullMethodName = "/kira.ubi.Query/QueryUBIRecordByName"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// QueryUBIRecords - query names of all UBIRecords
	QueryUBIRecords(ctx context.Context, in *QueryUBIRecordsRequest, opts ...grpc.CallOption) (*QueryUBIRecordsResponse, error)
	// QueryUBIRecordByName - query specific UBIRecord by name
	QueryUBIRecordByName(ctx context.Context, in *QueryUBIRecordByNameRequest, opts ...grpc.CallOption) (*QueryUBIRecordByNameResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryUBIRecords(ctx context.Context, in *QueryUBIRecordsRequest, opts ...grpc.CallOption) (*QueryUBIRecordsResponse, error) {
	out := new(QueryUBIRecordsResponse)
	err := c.cc.Invoke(ctx, Query_QueryUBIRecords_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryUBIRecordByName(ctx context.Context, in *QueryUBIRecordByNameRequest, opts ...grpc.CallOption) (*QueryUBIRecordByNameResponse, error) {
	out := new(QueryUBIRecordByNameResponse)
	err := c.cc.Invoke(ctx, Query_QueryUBIRecordByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// QueryUBIRecords - query names of all UBIRecords
	QueryUBIRecords(context.Context, *QueryUBIRecordsRequest) (*QueryUBIRecordsResponse, error)
	// QueryUBIRecordByName - query specific UBIRecord by name
	QueryUBIRecordByName(context.Context, *QueryUBIRecordByNameRequest) (*QueryUBIRecordByNameResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) QueryUBIRecords(context.Context, *QueryUBIRecordsRequest) (*QueryUBIRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUBIRecords not implemented")
}
func (UnimplementedQueryServer) QueryUBIRecordByName(context.Context, *QueryUBIRecordByNameRequest) (*QueryUBIRecordByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryUBIRecordByName not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_QueryUBIRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUBIRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryUBIRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QueryUBIRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryUBIRecords(ctx, req.(*QueryUBIRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryUBIRecordByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUBIRecordByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryUBIRecordByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_QueryUBIRecordByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryUBIRecordByName(ctx, req.(*QueryUBIRecordByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kira.ubi.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryUBIRecords",
			Handler:    _Query_QueryUBIRecords_Handler,
		},
		{
			MethodName: "QueryUBIRecordByName",
			Handler:    _Query_QueryUBIRecordByName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kira/ubi/query.proto",
}
