// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: kira/basket/proposal.proto

package types

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// proposal to create a token basket
type ProposalCreateBasket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basket *Basket `protobuf:"bytes,1,opt,name=basket,proto3" json:"basket,omitempty"`
}

func (x *ProposalCreateBasket) Reset() {
	*x = ProposalCreateBasket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_basket_proposal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalCreateBasket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalCreateBasket) ProtoMessage() {}

func (x *ProposalCreateBasket) ProtoReflect() protoreflect.Message {
	mi := &file_kira_basket_proposal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalCreateBasket.ProtoReflect.Descriptor instead.
func (*ProposalCreateBasket) Descriptor() ([]byte, []int) {
	return file_kira_basket_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *ProposalCreateBasket) GetBasket() *Basket {
	if x != nil {
		return x.Basket
	}
	return nil
}

// proposal to edit properties of the basket
type ProposalEditBasket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basket *Basket `protobuf:"bytes,1,opt,name=basket,proto3" json:"basket,omitempty"`
}

func (x *ProposalEditBasket) Reset() {
	*x = ProposalEditBasket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_basket_proposal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalEditBasket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalEditBasket) ProtoMessage() {}

func (x *ProposalEditBasket) ProtoReflect() protoreflect.Message {
	mi := &file_kira_basket_proposal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalEditBasket.ProtoReflect.Descriptor instead.
func (*ProposalEditBasket) Descriptor() ([]byte, []int) {
	return file_kira_basket_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *ProposalEditBasket) GetBasket() *Basket {
	if x != nil {
		return x.Basket
	}
	return nil
}

// proposal to withdraw surplus of one or all tokens in the `surplus` array of
// the basket to a specific wallet or a spending pool
type ProposalBasketWithdrawSurplus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketIds      []uint64 `protobuf:"varint,1,rep,packed,name=basket_ids,json=basketIds,proto3" json:"basket_ids,omitempty"`
	WithdrawTarget string   `protobuf:"bytes,2,opt,name=withdraw_target,json=withdrawTarget,proto3" json:"withdraw_target,omitempty"`
}

func (x *ProposalBasketWithdrawSurplus) Reset() {
	*x = ProposalBasketWithdrawSurplus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_basket_proposal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalBasketWithdrawSurplus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalBasketWithdrawSurplus) ProtoMessage() {}

func (x *ProposalBasketWithdrawSurplus) ProtoReflect() protoreflect.Message {
	mi := &file_kira_basket_proposal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalBasketWithdrawSurplus.ProtoReflect.Descriptor instead.
func (*ProposalBasketWithdrawSurplus) Descriptor() ([]byte, []int) {
	return file_kira_basket_proposal_proto_rawDescGZIP(), []int{2}
}

func (x *ProposalBasketWithdrawSurplus) GetBasketIds() []uint64 {
	if x != nil {
		return x.BasketIds
	}
	return nil
}

func (x *ProposalBasketWithdrawSurplus) GetWithdrawTarget() string {
	if x != nil {
		return x.WithdrawTarget
	}
	return ""
}

var File_kira_basket_proposal_proto protoreflect.FileDescriptor

var file_kira_basket_proposal_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6b, 0x69, 0x72, 0x61, 0x2f, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6b, 0x69,
	0x72, 0x61, 0x2e, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x19, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x6b, 0x69, 0x72,
	0x61, 0x2f, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2f, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x12, 0x31, 0x0a,
	0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6b, 0x69, 0x72, 0x61, 0x2e, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x42, 0x04, 0xc8, 0xde, 0x1f, 0x00, 0x52, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x22, 0x47, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x45, 0x64, 0x69, 0x74,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x69, 0x72, 0x61, 0x2e, 0x62, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x42, 0x04, 0xc8, 0xde, 0x1f,
	0x00, 0x52, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x22, 0x67, 0x0a, 0x1d, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x61, 0x6c, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x53, 0x75, 0x72, 0x70, 0x6c, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x77, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4b, 0x69, 0x72, 0x61, 0x43, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x6b, 0x61, 0x69, 0x2f,
	0x78, 0x2f, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kira_basket_proposal_proto_rawDescOnce sync.Once
	file_kira_basket_proposal_proto_rawDescData = file_kira_basket_proposal_proto_rawDesc
)

func file_kira_basket_proposal_proto_rawDescGZIP() []byte {
	file_kira_basket_proposal_proto_rawDescOnce.Do(func() {
		file_kira_basket_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(file_kira_basket_proposal_proto_rawDescData)
	})
	return file_kira_basket_proposal_proto_rawDescData
}

var file_kira_basket_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kira_basket_proposal_proto_goTypes = []interface{}{
	(*ProposalCreateBasket)(nil),          // 0: kira.basket.ProposalCreateBasket
	(*ProposalEditBasket)(nil),            // 1: kira.basket.ProposalEditBasket
	(*ProposalBasketWithdrawSurplus)(nil), // 2: kira.basket.ProposalBasketWithdrawSurplus
	(*Basket)(nil),                        // 3: kira.basket.Basket
}
var file_kira_basket_proposal_proto_depIdxs = []int32{
	3, // 0: kira.basket.ProposalCreateBasket.basket:type_name -> kira.basket.Basket
	3, // 1: kira.basket.ProposalEditBasket.basket:type_name -> kira.basket.Basket
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kira_basket_proposal_proto_init() }
func file_kira_basket_proposal_proto_init() {
	if File_kira_basket_proposal_proto != nil {
		return
	}
	file_kira_basket_basket_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kira_basket_proposal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalCreateBasket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_basket_proposal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalEditBasket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_basket_proposal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalBasketWithdrawSurplus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kira_basket_proposal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kira_basket_proposal_proto_goTypes,
		DependencyIndexes: file_kira_basket_proposal_proto_depIdxs,
		MessageInfos:      file_kira_basket_proposal_proto_msgTypes,
	}.Build()
	File_kira_basket_proposal_proto = out.File
	file_kira_basket_proposal_proto_rawDesc = nil
	file_kira_basket_proposal_proto_goTypes = nil
	file_kira_basket_proposal_proto_depIdxs = nil
}
