// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: kira/bridge/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_ChangeCosmosEthereum_FullMethodName = "/kira.bridge.Msg/ChangeCosmosEthereum"
	Msg_ChangeEthereumCosmos_FullMethodName = "/kira.bridge.Msg/ChangeEthereumCosmos"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	ChangeCosmosEthereum(ctx context.Context, in *MsgChangeCosmosEthereum, opts ...grpc.CallOption) (*MsgChangeCosmosEthereumResponse, error)
	ChangeEthereumCosmos(ctx context.Context, in *MsgChangeEthereumCosmos, opts ...grpc.CallOption) (*MsgChangeEthereumCosmosResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ChangeCosmosEthereum(ctx context.Context, in *MsgChangeCosmosEthereum, opts ...grpc.CallOption) (*MsgChangeCosmosEthereumResponse, error) {
	out := new(MsgChangeCosmosEthereumResponse)
	err := c.cc.Invoke(ctx, Msg_ChangeCosmosEthereum_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ChangeEthereumCosmos(ctx context.Context, in *MsgChangeEthereumCosmos, opts ...grpc.CallOption) (*MsgChangeEthereumCosmosResponse, error) {
	out := new(MsgChangeEthereumCosmosResponse)
	err := c.cc.Invoke(ctx, Msg_ChangeEthereumCosmos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	ChangeCosmosEthereum(context.Context, *MsgChangeCosmosEthereum) (*MsgChangeCosmosEthereumResponse, error)
	ChangeEthereumCosmos(context.Context, *MsgChangeEthereumCosmos) (*MsgChangeEthereumCosmosResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) ChangeCosmosEthereum(context.Context, *MsgChangeCosmosEthereum) (*MsgChangeCosmosEthereumResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeCosmosEthereum not implemented")
}
func (UnimplementedMsgServer) ChangeEthereumCosmos(context.Context, *MsgChangeEthereumCosmos) (*MsgChangeEthereumCosmosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeEthereumCosmos not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_ChangeCosmosEthereum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChangeCosmosEthereum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChangeCosmosEthereum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ChangeCosmosEthereum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChangeCosmosEthereum(ctx, req.(*MsgChangeCosmosEthereum))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ChangeEthereumCosmos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgChangeEthereumCosmos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ChangeEthereumCosmos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ChangeEthereumCosmos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ChangeEthereumCosmos(ctx, req.(*MsgChangeEthereumCosmos))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kira.bridge.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeCosmosEthereum",
			Handler:    _Msg_ChangeCosmosEthereum_Handler,
		},
		{
			MethodName: "ChangeEthereumCosmos",
			Handler:    _Msg_ChangeEthereumCosmos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kira/bridge/tx.proto",
}
