// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.1
// source: kira/tokens/alias.proto

package types

import (
	_ "github.com/gogo/protobuf/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenAlias struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol      string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`            // Ticker (eg. ATOM, KEX, BTC)
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                // Token Name (e.g. Cosmos, Kira, Bitcoin)
	Icon        string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`                // Graphical Symbol (url link to graphics)
	Decimals    uint32   `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`       // Integer number of max decimals
	Denoms      []string `protobuf:"bytes,5,rep,name=denoms,proto3" json:"denoms,omitempty"`            // An array of token denoms to be aliased
	Invalidated bool     `protobuf:"varint,6,opt,name=invalidated,proto3" json:"invalidated,omitempty"` // flag that the token is invalidated or not
}

func (x *TokenAlias) Reset() {
	*x = TokenAlias{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_tokens_alias_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAlias) ProtoMessage() {}

func (x *TokenAlias) ProtoReflect() protoreflect.Message {
	mi := &file_kira_tokens_alias_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAlias.ProtoReflect.Descriptor instead.
func (*TokenAlias) Descriptor() ([]byte, []int) {
	return file_kira_tokens_alias_proto_rawDescGZIP(), []int{0}
}

func (x *TokenAlias) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenAlias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenAlias) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *TokenAlias) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenAlias) GetDenoms() []string {
	if x != nil {
		return x.Denoms
	}
	return nil
}

func (x *TokenAlias) GetInvalidated() bool {
	if x != nil {
		return x.Invalidated
	}
	return false
}

type MsgUpsertTokenAlias struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol      string   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`            // Ticker (eg. ATOM, KEX, BTC)
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                // Token Name (e.g. Cosmos, Kira, Bitcoin)
	Icon        string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`                // Graphical Symbol (url link to graphics)
	Decimals    uint32   `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`       // Integer number of max decimals
	Denoms      []string `protobuf:"bytes,5,rep,name=denoms,proto3" json:"denoms,omitempty"`            // An array of token denoms to be aliased
	Invalidated bool     `protobuf:"varint,6,opt,name=invalidated,proto3" json:"invalidated,omitempty"` // flag that the token is invalidated or not
	Proposer    []byte   `protobuf:"bytes,7,opt,name=proposer,proto3" json:"proposer,omitempty"`
}

func (x *MsgUpsertTokenAlias) Reset() {
	*x = MsgUpsertTokenAlias{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kira_tokens_alias_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgUpsertTokenAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpsertTokenAlias) ProtoMessage() {}

func (x *MsgUpsertTokenAlias) ProtoReflect() protoreflect.Message {
	mi := &file_kira_tokens_alias_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpsertTokenAlias.ProtoReflect.Descriptor instead.
func (*MsgUpsertTokenAlias) Descriptor() ([]byte, []int) {
	return file_kira_tokens_alias_proto_rawDescGZIP(), []int{1}
}

func (x *MsgUpsertTokenAlias) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MsgUpsertTokenAlias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MsgUpsertTokenAlias) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MsgUpsertTokenAlias) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *MsgUpsertTokenAlias) GetDenoms() []string {
	if x != nil {
		return x.Denoms
	}
	return nil
}

func (x *MsgUpsertTokenAlias) GetInvalidated() bool {
	if x != nil {
		return x.Invalidated
	}
	return false
}

func (x *MsgUpsertTokenAlias) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

var File_kira_tokens_alias_proto protoreflect.FileDescriptor

var file_kira_tokens_alias_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6b, 0x69, 0x72, 0x61, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x2f, 0x61, 0x6c,
	0x69, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6b, 0x69, 0x72, 0x61, 0x2e,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a,
	0x0a, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6e, 0x6f, 0x6d,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x73, 0x12,
	0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x22, 0x8d, 0x02, 0x0a, 0x13, 0x4d, 0x73, 0x67, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x63,
	0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x73, 0x12, 0x20, 0x0a,
	0x0b, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x60, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0c, 0x42, 0x44, 0xf2, 0xde, 0x1f, 0x0f, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x70, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x65, 0x72, 0x22, 0xfa, 0xde, 0x1f, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x63,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x65,
	0x72, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4b, 0x69, 0x72, 0x61, 0x43, 0x6f, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x6b, 0x61, 0x69, 0x2f, 0x78,
	0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kira_tokens_alias_proto_rawDescOnce sync.Once
	file_kira_tokens_alias_proto_rawDescData = file_kira_tokens_alias_proto_rawDesc
)

func file_kira_tokens_alias_proto_rawDescGZIP() []byte {
	file_kira_tokens_alias_proto_rawDescOnce.Do(func() {
		file_kira_tokens_alias_proto_rawDescData = protoimpl.X.CompressGZIP(file_kira_tokens_alias_proto_rawDescData)
	})
	return file_kira_tokens_alias_proto_rawDescData
}

var file_kira_tokens_alias_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kira_tokens_alias_proto_goTypes = []interface{}{
	(*TokenAlias)(nil),          // 0: kira.tokens.TokenAlias
	(*MsgUpsertTokenAlias)(nil), // 1: kira.tokens.MsgUpsertTokenAlias
}
var file_kira_tokens_alias_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kira_tokens_alias_proto_init() }
func file_kira_tokens_alias_proto_init() {
	if File_kira_tokens_alias_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kira_tokens_alias_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenAlias); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kira_tokens_alias_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgUpsertTokenAlias); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kira_tokens_alias_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kira_tokens_alias_proto_goTypes,
		DependencyIndexes: file_kira_tokens_alias_proto_depIdxs,
		MessageInfos:      file_kira_tokens_alias_proto_msgTypes,
	}.Build()
	File_kira_tokens_alias_proto = out.File
	file_kira_tokens_alias_proto_rawDesc = nil
	file_kira_tokens_alias_proto_goTypes = nil
	file_kira_tokens_alias_proto_depIdxs = nil
}
